### PR TITLE
Implement ESMpy mask handling

### PR DESCRIPTION
**Pull request by jhamman**
This comes from the discussion in #22. It is intended to help users specify masks for the valid cells in the source and/or destination grids. It does this in the following way:

- looks for `mask` variable in `ds_in` and `ds_out`
- if `mask` variable is present, it adds that mask to the ESMF grid object
- specifies the mask values in the `ESMF.Regrid()` call. 

I've been testing this and it seems to be headed in the right direction. There are certainly additional features/tests/docs that this will need but I'm putting up here to aid in our discussion.

### CODE REVIEW

**Comment by jhamman** [comment]
Here's the same example I showed in #22, but using a mask.

image

I haven't figured out yet how to mask the grid cells with nans where there were no valid weights. Perhaps @bekozi knows where to get that info from the ESMpy objects?

**Comment by bekozi** [comment]
> I haven't figured out yet how to mask the grid cells with nans where there were no valid weights. Perhaps @bekozi knows where to get that info from the ESMpy objects?

We could potentially pull in the unmapped destination list to ESMPy, but I think it is easier to use fill values (or nans) during the sparse matrix multiplication. Basically, fill the destination matrix with nans before applying the sparse matrix. Afterwards, if the masks are set up correctly, only the mapped values will be non-nan. See [filling](https://github.com/NCPP/ocgis/blob/master/src/ocgis/regrid/base.py#L715) and [finding](https://github.com/NCPP/ocgis/blob/master/src/ocgis/regrid/base.py#L731-L738) for a mildly relevant examples.

**Comment by JiaweiZhuang** [comment]
Thanks for the PR (the first PR for xESMF)! 

I still have some concerns: https://github.com/JiaweiZhuang/xESMF/issues/22#issuecomment-400175414. Let's continue the discussion in the main issue.

**Comment by rabernat** [comment]
@jhamman - this PR was discussed today at the xESMF dev meeting. There was a consensus that it's a very important feature. 

Could you let us know whether you plan to keep working on the PR? Do you need any help from the dev team? If you don't have time to finish it, let us know so someone else can take it over.

**Comment by jhamman** [comment]
Thanks for the ping. I'm not likely to have time to pick this up in the near future so would welcome someone else stepping in if there is time/interest.

**Comment by rabernat** [comment]
What is the difference between this and #82? Does that supersede this?

If we want to move forward with this PR, I recommend it be moved to https://github.com/pangeo-data/xESMF? Unfortunately this has to be done manually.

**Comment by raphaeldussin** [comment]
Comparing across forks:

JiaweiZhuang:masking is up to date with all commits from jhamman:feature/masks.

so this PR can be closed

**Pull request closed without merging**
